In [1]:
import pandas as pd
import numpy as np

In [2]:
hotel = pd.read_csv('C:/Users/samsc/Desktop/Hotel-Cancellations-Project-ADS-505/hotel_bookings.csv')
hotel.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,no,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,7/1/2015
1,Resort Hotel,no,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,7/1/2015
2,Resort Hotel,no,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,7/2/2015
3,Resort Hotel,no,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,7/2/2015
4,Resort Hotel,no,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,7/3/2015

In [3]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  object
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(15), object(13)
memory usage: 29.1+ MB

In [4]:
hotel.isna().sum() #clearly see where the NAs are at

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [5]:
#hotel['adults'].value_counts()
#hotel['children'].value_counts()
#hotel['babies'].value_counts()
#hotel['meal'].value_counts() #-- > https://dmcquote.com/blog/post/hotel-meal-plans-guide-bb-hb-fb-ai
#hotel['country'].value_counts()
#hotel['market_segment'].value_counts() #how someone booked their hotel trip
#hotel['distribution_channel'].value_counts()
#hotel['is_repeated_guest'].value_counts()
#hotel['previous_cancellations'].value_counts() #how many times a customer has cancelled
#hotel['previous_bookings_not_canceled'].value_counts() #how many customers did not cancel their booking previous to staying at said hotel
#hotel['assigned_room_type'].value_counts()
#hotel['booking_changes'].value_counts()
#hotel['deposit_type'].value_counts()
#hotel['agent'].value_counts()
#hotel['company'].value_counts()
#hotel['days_in_waiting_list'].value_counts()  #debatable dropping this column because of how little days people are waiting (could feature engineer it)
#hotel['customer_type'].value_counts()
# hotel['adr'].value_counts()
# hotel['required_car_parking_spaces'].value_counts() #powerful predictor
# hotel['total_of_special_requests'].value_counts() 
#hotel['reservation_status'].value_counts() #drop this column because it is our outcome variable
#hotel['reservation_status_date'].value_counts() #drop this column because it is part of the outcome variable

In [6]:
#What to do about missing data -> 
#children impute missing value with zero(since they are so few missing values and most of the data shows that customers are not children 
#and/or with children)
impute_with_zero = (hotel['children'].isna() == True)
impute_with_zero = impute_with_zero[impute_with_zero == True]
hotel.loc[impute_with_zero.index, 'children'] = 0
hotel['children'].isna().sum()

np.int64(0)

In [7]:
#How to deal with country 
hotel['country'] = hotel['country'].fillna('Unknown') #fill it with unknown as it shouldn't impact the data too much
hotel['country'].isna().sum()

np.int64(0)

In [8]:
#How to deal with agent feature
hotel['agent'] = hotel['agent'].fillna(-1) #negative one means that the 
hotel['agent'].isna().sum()

np.int64(0)

In [9]:
#25. company -> columns contains ID of the company that made the booking  
#feature 25 has over 90% missing data so we can create a binary variable that shows whether the account is a company account

company_binary = (hotel['company'].isna() == True)
company_binary = company_binary[company_binary == True]
company_binary
hotel.loc[company_binary.index, 'company'] = 0
#hotel['company'].value_counts()
company_false = hotel['company'] != 0.0
#company_false.sum()
hotel.loc[company_false, 'company'] = 1
hotel['company'] = hotel['company'].astype('int')
hotel['company']
#hotel['company'].value_counts()

0         0
1         0
2         0
3         0
4         0
         ..
119385    0
119386    0
119387    0
119388    0
119389    0
Name: company, Length: 119390, dtype: int64

In [10]:
hotel.isna().sum() #no more missing data!!!

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

### Dropping columns

In [11]:
#dropping these two columns as the information they provid
#does not seem significant enough considering we have
#arrival_date_year and arrival_date_month
hotel = hotel.drop(columns=['arrival_date_week_number'
                    ,'arrival_date_day_of_month'])
hotel.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,no,342,2015,July,0,0,2,0.0,0,...,No Deposit,-1.0,0,0,Transient,0.0,0,0,Check-Out,7/1/2015
1,Resort Hotel,no,737,2015,July,0,0,2,0.0,0,...,No Deposit,-1.0,0,0,Transient,0.0,0,0,Check-Out,7/1/2015
2,Resort Hotel,no,7,2015,July,0,1,1,0.0,0,...,No Deposit,-1.0,0,0,Transient,75.0,0,0,Check-Out,7/2/2015
3,Resort Hotel,no,13,2015,July,0,1,1,0.0,0,...,No Deposit,304.0,0,0,Transient,75.0,0,0,Check-Out,7/2/2015
4,Resort Hotel,no,14,2015,July,0,2,2,0.0,0,...,No Deposit,240.0,0,0,Transient,98.0,0,1,Check-Out,7/3/2015

In [12]:
#dropping reservation_status and reservation_status_date because both of these columns allude to directly
#predicting the target variable is_canceled which we do not want a model with strong features that tell us
#the outcome based on these two features alone (not helpful for the business to improve hotel cancellation rate)
hotel = hotel.drop(columns=['reservation_status'
                    ,'reservation_status_date'])
hotel.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,no,342,2015,July,0,0,2,0.0,0,...,C,3,No Deposit,-1.0,0,0,Transient,0.0,0,0
1,Resort Hotel,no,737,2015,July,0,0,2,0.0,0,...,C,4,No Deposit,-1.0,0,0,Transient,0.0,0,0
2,Resort Hotel,no,7,2015,July,0,1,1,0.0,0,...,C,0,No Deposit,-1.0,0,0,Transient,75.0,0,0
3,Resort Hotel,no,13,2015,July,0,1,1,0.0,0,...,A,0,No Deposit,304.0,0,0,Transient,75.0,0,0
4,Resort Hotel,no,14,2015,July,0,2,2,0.0,0,...,A,0,No Deposit,240.0,0,0,Transient,98.0,0,1

In [13]:
#for features stays_in_weekend_nights and stays_in_week_nights we can feature engineer these two columns into 
#one where it is a binary feature on whether they stay the weekend or not
hotel['stays_in_weekend_nights'].value_counts()
weekend_nights_yes = hotel['stays_in_weekend_nights'] > 0
weekend_nights_yes = weekend_nights_yes[weekend_nights_yes == True]
hotel.loc[weekend_nights_yes.index, 'stays_in_weekend_nights'] = 1
hotel['stays_in_weekend_nights'].value_counts()

#drop stay_in_week_nights column as it is no longer needed
hotel = hotel.drop(columns=['stays_in_week_nights'])
hotel.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,stays_in_weekend_nights,adults,children,babies,meal,...,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,no,342,2015,July,0,2,0.0,0,BB,...,C,3,No Deposit,-1.0,0,0,Transient,0.0,0,0
1,Resort Hotel,no,737,2015,July,0,2,0.0,0,BB,...,C,4,No Deposit,-1.0,0,0,Transient,0.0,0,0
2,Resort Hotel,no,7,2015,July,0,1,0.0,0,BB,...,C,0,No Deposit,-1.0,0,0,Transient,75.0,0,0
3,Resort Hotel,no,13,2015,July,0,1,0.0,0,BB,...,A,0,No Deposit,304.0,0,0,Transient,75.0,0,0
4,Resort Hotel,no,14,2015,July,0,2,0.0,0,BB,...,A,0,No Deposit,240.0,0,0,Transient,98.0,0,1

In [14]:
#for features children and babies consider combining them into one group since individual they act the same
#(running this code multiple times will change results
hotel['children'] = hotel['children'] + hotel['babies']
hotel['children'] = hotel['children'].astype('int')

hotel = hotel.drop(columns=['babies'])
hotel.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,stays_in_weekend_nights,adults,children,meal,country,...,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,no,342,2015,July,0,2,0,BB,PRT,...,C,3,No Deposit,-1.0,0,0,Transient,0.0,0,0
1,Resort Hotel,no,737,2015,July,0,2,0,BB,PRT,...,C,4,No Deposit,-1.0,0,0,Transient,0.0,0,0
2,Resort Hotel,no,7,2015,July,0,1,0,BB,GBR,...,C,0,No Deposit,-1.0,0,0,Transient,75.0,0,0
3,Resort Hotel,no,13,2015,July,0,1,0,BB,GBR,...,A,0,No Deposit,304.0,0,0,Transient,75.0,0,0
4,Resort Hotel,no,14,2015,July,0,2,0,BB,GBR,...,A,0,No Deposit,240.0,0,0,Transient,98.0,0,1

In [15]:
#reserved_room feature worth discussing today

In [16]:
#adr 0 = budget, 1 = standard, 2 = premium 
hotel['adr'].value_counts()

adr_budget = hotel['adr'] <= 60.00
adr_budget = adr_budget[adr_budget == True]
adr_budget[adr_budget == True] = 0.0
adr_budget

adr_standard = (hotel['adr'] > 60.00) & (hotel['adr'] <= 120.00)
adr_standard = adr_standard[adr_standard == True]
adr_standard[adr_standard == True] = 1.0
adr_standard

adr_premium = hotel['adr'] > 120.00
adr_premium = adr_premium[adr_premium == True]
adr_premium[adr_premium == True] = 2.0
adr_premium

hotel.loc[adr_budget.index, 'adr'] = 0.0
hotel.loc[adr_standard.index, 'adr'] = 1.0
hotel.loc[adr_premium.index, 'adr'] = 2.0
hotel['adr'] = hotel['adr'].astype('int')
#hotel['adr'].value_counts()

C:\Users\samsc\AppData\Local\Temp\ipykernel_23760\2630491694.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  adr_budget[adr_budget == True] = 0.0
C:\Users\samsc\AppData\Local\Temp\ipykernel_23760\2630491694.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  adr_standard[adr_standard == True] = 1.0
C:\Users\samsc\AppData\Local\Temp\ipykernel_23760\2630491694.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  adr_premium[adr_premium == True] = 2.0

adr
1    68190
2    33211
0    17989
Name: count, dtype: int64